POST https://d0g-blog.herokuapp.com/users/login
Content-Type: application/json

{
    "username":"logan",
    "password":"1logan"
}



###
POST https://d0g-blog.herokuapp.com/users/register
Content-Type: application/json

{
    "username": "logan",
    "email": "logan@gmail.com",
    "password": "1logan"
}



###
POST https://d0g-blog.herokuapp.com/contact
Content-Type: application/json


{
    "name":"tursha",
    "email":"turshaarendse@gmail.com",
    "message":"hey baby hope you doing well tell your mommy i say hi aunty sherlin got sick"
}

###
GET http://localhost:5000/users

###

GET http://localhost:5000/comments


###

POST http://localhost:5000/posts
Content-Type: application/json
{
    "title": "Dog Shampoo",
    "description": "Best Shampoo for your dogs",
    "photo": "https://postimg.cc/SnRSBjn8",
    "CreatedBy": "CraigBraaf",
    "categories": "Dog Shampoo",
    "comments": "",
}

###
GET http://localhost:5000/users

###

DELETE http://localhost:5000/users/6233290a687951f24c4b4ebf
Content-Type: application/json

{
    "username": "Craig",
    "email": "braafcraig@gmail.com",
    "password": "braaf2022"
}